# Generated by Django 4.2.6 on 2023-10-19 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.uplod_files


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('MOBILE PHONES', 'Mobile Phones'), ('COMPUTERS', 'Computers'), ('ELECTRONICS', 'Electronics'), ('HOME_APPLIANCES', 'Home Appliances'), ('SECURITY', 'Security'), ('AUTOMOBILES', 'Automobiles'), ('FURNITURE', 'Furniture'), ('CLOTHING', 'Clothing'), ('SHOES', 'Shoes'), ('ACCESSORIES', 'Accessories'), ('SPORT', 'Sport'), ('FOOD', 'Food')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(blank=True, max_length=255, null=True)),
                ('count', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=1, max_digits=15)),
                ('currency', models.CharField(choices=[('amd', 'AMD'), ('usd', 'USD'), ('rub', 'RUB'), ('yuan', 'YUAN')], max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('BIG', 'big'), ('SMOL', 'small')], max_length=50)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.DecimalField(decimal_places=1, max_digits=2)),
                ('photo', models.ImageField(upload_to=helpers.uplod_files.upload_product_image)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.categories')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
